name: master

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git pull
          mvn -q -s settings.xml clean install

      - name: Upload app bundle
        uses: actions/upload-artifact@v3
        with:
          name: appbundle
          path: target/*.jar

  deploy-test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - name: JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Get artigact
        uses: actions/download-artifact@v3
        with:
          name: appbundle
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku plugins:install @heroku-cli/plugin-java
      - name: Heroku-Deploy-Test
        env:
          API_KEY: ${{secrets.API_KEY_TEST}}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_TEST }}
          CLOUDAMQP_URL: ${{secrets.CLOUDAMQP_URL_TEST}}
          HEROKU_APP: wutsi-store-bff-test
        run: |
          heroku apps | grep ${HEROKU_APP} && echo 'app: ${HEROKU_APP} exists' ||  heroku apps:create ${HEROKU_APP}
          heroku buildpacks:clear --app ${HEROKU_APP}
          heroku buildpacks:add heroku/jvm --app ${HEROKU_APP}
          heroku config:set --app ${HEROKU_APP} APP_PROFILE=test
          heroku config:set --app ${HEROKU_APP} CLOUDAMQP_URL=${CLOUDAMQP_URL}
          heroku config:set --app ${HEROKU_APP} API_KEY=${API_KEY}
          heroku addons -a ${HEROKU_APP} | grep papertrail && echo 'addon: papertrail exists' ||  heroku addons:create papertrail -a ${HEROKU_APP}
          heroku deploy:jar target/wutsi-store-bff.jar --app ${HEROKU_APP}
      - name: Health check
        env:
          HEROKU_APP: wutsi-store-bff-test
        run: |
          sleep 90
          curl -sSf https://${HEROKU_APP}.herokuapp.com/actuator/health >> /dev/null

  deploy-test-notification:
    runs-on: ubuntu-latest
    needs: [ deploy-test ]
    if: always()
    steps:
      - name: Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: wutsi-store-bff-test
          SLACK_MESSAGE: Heroku Deployment in TEST
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}


  deploy-prod:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - name: JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Get artigact
        uses: actions/download-artifact@v3
        with:
          name: appbundle
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku plugins:install @heroku-cli/plugin-java
      - name: Heroku-Deploy-Prod
        env:
          API_KEY: ${{secrets.API_KEY_PROD}}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_PROD }}
          CLOUDAMQP_URL: ${{secrets.CLOUDAMQP_URL_PROD}}
          HEROKU_APP: wutsi-store-bff-prod
        run: |
          heroku apps | grep ${HEROKU_APP} && echo 'app: ${HEROKU_APP} exists' ||  heroku apps:create ${HEROKU_APP}
          heroku buildpacks:clear --app ${HEROKU_APP}
          heroku buildpacks:add heroku/jvm --app ${HEROKU_APP}
          heroku config:set --app ${HEROKU_APP} APP_PROFILE=prod
          heroku config:set --app ${HEROKU_APP} CLOUDAMQP_URL=${CLOUDAMQP_URL}
          heroku config:set --app ${HEROKU_APP} API_KEY=${API_KEY}
          heroku addons -a ${HEROKU_APP} | grep papertrail && echo 'addon: papertrail exists' ||  heroku addons:create papertrail -a ${HEROKU_APP}
          heroku deploy:jar target/wutsi-store-bff.jar --app ${HEROKU_APP}
      - name: Health check
        env:
          HEROKU_APP: wutsi-store-bff-prod
          sleep 90
          curl -sSf https://${HEROKU_APP}.herokuapp.com/actuator/health >> /dev/null


  deploy-prod-notification:
    runs-on: ubuntu-latest
    needs: [ deploy-prod ]
    if: always()
    steps:
      - name: Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: wutsi-store-bff-prod
          SLACK_MESSAGE: Heroku Deployment in PROD
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}


  cleanup:
    runs-on: ubuntu-latest
    needs: [ deploy-test, deploy-prod ]
    if: always()
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: appbundle
